package com.ecart.controller.order;

import com.ecart.dao.FeedbackDAO;
import com.ecart.dao.OrderDAO;
import com.ecart.model.Feedback;
import com.ecart.model.Order;
import com.ecart.model.OrderStatus;
import com.ecart.util.ValidationUtil;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.sql.Timestamp;

@WebServlet("/customer/feedback/*")
public class FeedbackServlet extends HttpServlet {
    private FeedbackDAO feedbackDAO;
    private OrderDAO orderDAO;

    @Override
    public void init() throws ServletException {
        feedbackDAO = new FeedbackDAO();
        orderDAO = new OrderDAO();
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession session = request.getSession(false);
        if (session == null || session.getAttribute("userId") == null) {
            response.sendRedirect(request.getContextPath() + "/login");
            return;
        }

        String orderId = request.getParameter("orderId");
        if (orderId == null || orderId.trim().isEmpty()) {
            response.sendRedirect("orders");
            return;
        }

        // Get the order details
        Order order = orderDAO.getOrderById(orderId);
        if (order == null || !order.getCustomerId().equals(session.getAttribute("userId"))) {
            request.setAttribute("error", "Invalid order");
            response.sendRedirect("orders");
            return;
        }

        // Check if order is delivered
        if (order.getStatus() != OrderStatus.DELIVERED) {
            request.setAttribute("error", "Feedback can only be given for delivered orders");
            response.sendRedirect("orders");
            return;
        }

        // Check if feedback already exists
        Feedback existingFeedback = feedbackDAO.getFeedbackByOrderId(orderId);
        if (existingFeedback != null) {
            request.setAttribute("feedback", existingFeedback);
        }

        request.setAttribute("order", order);
        request.getRequestDispatcher("/customer/feedback.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession session = request.getSession(false);
        if (session == null || session.getAttribute("userId") == null) {
            response.sendRedirect(request.getContextPath() + "/login");
            return;
        }

        String orderId = request.getParameter("orderId");
        String description = request.getParameter("description");
        String ratingStr = request.getParameter("rating");

        // Validate inputs
        if (!validateInputs(request, orderId, description, ratingStr)) {
            doGet(request, response);
            return;
        }

        int rating = Integer.parseInt(ratingStr);
        String userId = (String) session.getAttribute("userId");

        // Verify order belongs to user and is delivered
        Order order = orderDAO.getOrderById(orderId);
        if (order == null || !order.getCustomerId().equals(userId)) {
            request.setAttribute("error", "Invalid order");
            doGet(request, response);
            return;
        }

        if (order.getStatus() != OrderStatus.DELIVERED) {
            request.setAttribute("error", "Feedback can only be given for delivered orders");
            doGet(request, response);
            return;
        }

        // Create or update feedback
        Feedback feedback = new Feedback(
            0, // ID will be generated by database
            orderId,
            userId,
            description,
            rating,
            new Timestamp(System.currentTimeMillis())
        );

        boolean success = feedbackDAO.getFeedbackByOrderId(orderId) != null ? 
                         feedbackDAO.updateFeedback(feedback) : 
                         feedbackDAO.addFeedback(feedback);

        if (success) {
            request.setAttribute("success", "Feedback submitted successfully");
        } else {
            request.setAttribute("error", "Failed to submit feedback. Please try again.");
        }

        response.sendRedirect("orders");
    }

    private boolean validateInputs(HttpServletRequest request, String orderId, 
                                 String description, String ratingStr) {
        if (orderId == null || orderId.trim().isEmpty()) {
            request.setAttribute("error", "Order ID is required");
            return false;
        }

        if (!ValidationUtil.isValidDescription(description)) {
            request.setAttribute("error", 
                "Description must be between 10 and 500 characters");
            return false;
        }

        try {
            int rating = Integer.parseInt(ratingStr);
            if (!ValidationUtil.isValidFeedbackRating(rating)) {
                request.setAttribute("error", "Rating must be between 1 and 5");
                return false;
            }
        } catch (NumberFormatException e) {
            request.setAttribute("error", "Invalid rating value");
            return false;
        }

        return true;
    }
}
